import { describe, it, expect } from 'vitest';
import ts from 'typescript';
import { generateSecretsDts } from './secrets-dts.js';
import type { EnvironmentMetadata, GenerateSecretsDtsOptions } from './secrets-dts.js';

function makeOptions(
  environments: EnvironmentMetadata[],
  endpoint = 'https://orch.example.com',
): GenerateSecretsDtsOptions {
  return {
    environments,
    endpoint,
    generatedAt: new Date('2026-01-15T10:00:00Z'),
  };
}

describe('generateSecretsDts', () => {
  it('generates valid module augmentation with multiple environments', () => {
    const output = generateSecretsDts(
      makeOptions([
        { name: 'production', keys: ['DB_HOST', 'DB_PASSWORD', 'API_KEY'] },
        { name: 'staging', keys: ['DB_HOST', 'DB_PASSWORD', 'SLACK_TOKEN'] },
      ]),
    );

    expect(output).toContain("declare module '@kici-dev/sdk'");
    expect(output).toContain('interface KnownSecretKeys');
    expect(output).toContain('interface EnvironmentSecrets');

    // KnownSecretKeys: union of all keys
    expect(output).toContain('DB_HOST: string;');
    expect(output).toContain('DB_PASSWORD: string;');
    expect(output).toContain('API_KEY: string;');
    expect(output).toContain('SLACK_TOKEN: string;');

    // JSDoc comments showing source environments
    expect(output).toContain('/** From environment: production, staging */');
    expect(output).toContain('/** From environment: production */');
    expect(output).toContain('/** From environment: staging */');

    // EnvironmentSecrets: per-environment key unions
    expect(output).toContain("production: 'DB_HOST' | 'DB_PASSWORD' | 'API_KEY';");
    expect(output).toContain("staging: 'DB_HOST' | 'DB_PASSWORD' | 'SLACK_TOKEN';");
  });

  it('generates empty interfaces when environments array is empty', () => {
    const output = generateSecretsDts(makeOptions([]));

    expect(output).toContain("declare module '@kici-dev/sdk'");
    expect(output).toContain('interface KnownSecretKeys {');
    expect(output).toContain('interface EnvironmentSecrets {');

    // Interfaces should be empty (just open/close braces)
    expect(output).toMatch(/interface KnownSecretKeys \{\n\s*\}/);
    expect(output).toMatch(/interface EnvironmentSecrets \{\n\s*\}/);
  });

  it('uses quoted property syntax for non-identifier key names', () => {
    const output = generateSecretsDts(
      makeOptions([{ name: 'my-env', keys: ['my-key', 'some.dotted', 'VALID_KEY'] }]),
    );

    // Non-identifiers should be quoted in KnownSecretKeys
    expect(output).toContain("'my-key': string;");
    expect(output).toContain("'some.dotted': string;");
    // Environment name with dash should also be quoted
    expect(output).toContain("'my-env':");

    // Valid identifier should not be quoted as a property name in KnownSecretKeys
    expect(output).toContain('VALID_KEY: string;');

    // EnvironmentSecrets uses key unions (all quoted as string literals)
    expect(output).toContain("'my-key' | 'some.dotted' | 'VALID_KEY'");
  });

  it('includes metadata header with endpoint and timestamp', () => {
    const output = generateSecretsDts(makeOptions([], 'https://my-orch.example.com'));

    expect(output).toContain('// @generated by kici types -- DO NOT EDIT');
    expect(output).toContain('// Source: https://my-orch.example.com');
    expect(output).toContain('// Generated: 2026-01-15T10:00:00.000Z');
    expect(output).toContain('// Run `kici types` to refresh');
  });

  it('generates correct output for a single environment with multiple keys', () => {
    const output = generateSecretsDts(
      makeOptions([{ name: 'database', keys: ['HOST', 'PORT', 'USER', 'PASS'] }]),
    );

    // All keys should be in KnownSecretKeys
    expect(output).toContain('HOST: string;');
    expect(output).toContain('PORT: string;');
    expect(output).toContain('USER: string;');
    expect(output).toContain('PASS: string;');

    // All keys should reference single environment
    expect(output).toContain('/** From environment: database */');

    // EnvironmentSecrets should have the key union
    expect(output).toContain("database: 'HOST' | 'PORT' | 'USER' | 'PASS';");
  });

  it('ends with a trailing newline', () => {
    const output = generateSecretsDts(makeOptions([]));
    expect(output.endsWith('\n')).toBe(true);
  });

  it('deduplicates keys in KnownSecretKeys across environments', () => {
    const output = generateSecretsDts(
      makeOptions([
        { name: 'a', keys: ['SHARED', 'UNIQUE_A'] },
        { name: 'b', keys: ['SHARED', 'UNIQUE_B'] },
        { name: 'c', keys: ['SHARED'] },
      ]),
    );

    // SHARED should appear exactly once in KnownSecretKeys
    const knownSecretsMatch = output.match(/interface KnownSecretKeys \{([\s\S]*?)\}/);
    expect(knownSecretsMatch).not.toBeNull();
    const knownSecretsBlock = knownSecretsMatch![1];
    const sharedOccurrences = knownSecretsBlock.match(/SHARED: string;/g);
    expect(sharedOccurrences).toHaveLength(1);

    // But the JSDoc should list all three environments
    expect(output).toContain('/** From environment: a, b, c */');
  });

  it('uses never type for environments with no bound secrets', () => {
    const output = generateSecretsDts(
      makeOptions([
        { name: 'production', keys: ['DB_PASSWORD'] },
        { name: 'staging', keys: [] },
      ]),
    );

    expect(output).toContain("production: 'DB_PASSWORD';");
    expect(output).toContain('staging: never;');
  });

  it('escapes single quotes and backslashes in key and environment names', () => {
    const output = generateSecretsDts(
      makeOptions([{ name: "it's", keys: ["foo'bar", 'back\\slash'] }]),
    );

    // Property names should have escaped quotes
    expect(output).toContain("'it\\'s':");
    expect(output).toContain("'foo\\'bar': string;");
    expect(output).toContain("'back\\\\slash': string;");

    // Key union should also escape
    expect(output).toContain("'foo\\'bar' | 'back\\\\slash'");
  });

  it('does not generate KnownContexts interface', () => {
    const output = generateSecretsDts(makeOptions([{ name: 'production', keys: ['KEY'] }]));

    expect(output).not.toContain('KnownContexts');
  });

  it('emits a top-level export so the file is a module (augments, not shadows)', () => {
    const output = generateSecretsDts(makeOptions([{ name: 'production', keys: ['KEY'] }]));

    // A bare `export {};` on its own line makes the .d.ts a module, which turns
    // the `declare module '@kici-dev/sdk'` block into an augmentation instead of
    // an ambient declaration that would replace (shadow) the whole SDK.
    expect(output).toMatch(/^export \{\};$/m);
  });

  it('produces a source file TypeScript treats as a module', () => {
    const output = generateSecretsDts(makeOptions([{ name: 'production', keys: ['KEY'] }]));

    const sourceFile = ts.createSourceFile(
      'secrets.d.ts',
      output,
      ts.ScriptTarget.Latest,
      /* setParentNodes */ false,
    );

    // externalModuleIndicator is set iff TS parses the file as a module. If it
    // were undefined, the `declare module` block would shadow @kici-dev/sdk.
    expect(sourceFile.externalModuleIndicator).toBeTruthy();
  });
});
