/**
 * .d.ts generator for environment secret type augmentation.
 *
 * Produces a TypeScript declaration file that augments @kici-dev/sdk's
 * KnownSecretKeys and EnvironmentSecrets interfaces, enabling compile-time
 * autocomplete and type checking for `ctx.secrets.get()` and `ctx.secrets.expose()`
 * key names per environment.
 */

export interface EnvironmentMetadata {
  name: string;
  keys: string[];
}

interface GenerateSecretsDtsOptions {
  environments: EnvironmentMetadata[];
  endpoint: string;
  generatedAt: Date;
}

/**
 * Check if a string is a valid TypeScript identifier (unquoted property name).
 */
function isValidIdentifier(name: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

function escapeQuotes(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function formatProperty(name: string): string {
  return isValidIdentifier(name) ? name : `'${escapeQuotes(name)}'`;
}

/**
 * Build a map of key -> list of environment names that provide it.
 */
function buildKeySourceMap(environments: EnvironmentMetadata[]): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const env of environments) {
    for (const key of env.keys) {
      const sources = map.get(key);
      if (sources) {
        sources.push(env.name);
      } else {
        map.set(key, [env.name]);
      }
    }
  }
  return map;
}

/**
 * Generate a .d.ts string from environment metadata.
 *
 * The output augments @kici-dev/sdk's KnownSecretKeys and EnvironmentSecrets
 * interfaces, enabling compile-time autocomplete for secret keys per environment.
 *
 * @param options - Environment metadata, endpoint URL, and generation timestamp
 * @returns The .d.ts file content as a string
 */
export function generateSecretsDts(options: GenerateSecretsDtsOptions): string {
  const { environments, endpoint, generatedAt } = options;
  const lines: string[] = [];

  // Header comment
  lines.push('// @generated by kici types -- DO NOT EDIT');
  lines.push(`// Source: ${endpoint}`);
  lines.push(`// Generated: ${generatedAt.toISOString()}`);
  lines.push('// Run `kici types` to refresh');
  lines.push('');

  lines.push("declare module '@kici-dev/sdk' {");

  // KnownSecretKeys: union of all keys across all environments
  const keySourceMap = buildKeySourceMap(environments);
  lines.push('  interface KnownSecretKeys {');
  for (const [key, sources] of keySourceMap) {
    lines.push(`    /** From environment: ${sources.join(', ')} */`);
    lines.push(`    ${formatProperty(key)}: string;`);
  }
  lines.push('  }');

  lines.push('');

  // EnvironmentSecrets: each environment with its specific secret keys as union type
  lines.push('  interface EnvironmentSecrets {');
  for (const env of environments) {
    if (env.keys.length === 0) {
      lines.push(`    ${formatProperty(env.name)}: never;`);
    } else {
      const keyUnion = env.keys.map((k) => `'${escapeQuotes(k)}'`).join(' | ');
      lines.push(`    ${formatProperty(env.name)}: ${keyUnion};`);
    }
  }
  lines.push('  }');

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
