/**
 * .d.ts generator for context secret type augmentation.
 *
 * Produces a TypeScript declaration file that augments @kici-dev/sdk's
 * KnownSecretKeys and ContextSecrets interfaces, enabling compile-time
 * autocomplete and type checking for `ctx.secrets.get()` and `ctx.secrets.expose()`
 * key names per context.
 */

export interface ContextMetadata {
  name: string;
  keys: string[];
}

export interface GenerateSecretsDtsOptions {
  contexts: ContextMetadata[];
  endpoint: string;
  /**
   * Mark the output as an offline stub written when the Platform could not be
   * reached (unauthenticated, offline, or no active org). The header names it a
   * stub instead of a source URL so a reader can tell it from a real snapshot,
   * and the caller passes `contexts: []` so it augments no known keys.
   */
  offline?: boolean;
}

/**
 * Check if a string is a valid TypeScript identifier (unquoted property name).
 */
function isValidIdentifier(name: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

function escapeQuotes(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function formatProperty(name: string): string {
  return isValidIdentifier(name) ? name : `'${escapeQuotes(name)}'`;
}

/**
 * Build a map of key -> list of context names that provide it.
 */
function buildKeySourceMap(contexts: ContextMetadata[]): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const env of contexts) {
    for (const key of env.keys) {
      const sources = map.get(key);
      if (sources) {
        sources.push(env.name);
      } else {
        map.set(key, [env.name]);
      }
    }
  }
  return map;
}

/**
 * Generate a .d.ts string from context metadata.
 *
 * The output augments @kici-dev/sdk's KnownSecretKeys and ContextSecrets
 * interfaces, enabling compile-time autocomplete for secret keys per context.
 *
 * @param options - Context metadata, endpoint URL, and generation timestamp
 * @returns The .d.ts file content as a string
 */
export function generateSecretsDts(options: GenerateSecretsDtsOptions): string {
  const { contexts, endpoint, offline } = options;
  const lines: string[] = [];

  // Header comment. Deliberately carries no generation timestamp: the output is
  // a checked-in-adjacent generated artifact, so it must be deterministic —
  // `kici types` / `kici compile` regenerating it must never produce a spurious
  // diff. The `Run kici types to refresh` line already tells the reader it is
  // regenerable.
  lines.push('// @generated by kici types -- DO NOT EDIT');
  if (offline) {
    lines.push('// Source: offline stub -- Platform unreachable, no known secret keys');
  } else {
    lines.push(`// Source: ${endpoint}`);
  }
  lines.push('// Run `kici types` to refresh');
  lines.push('');

  lines.push("declare module '@kici-dev/sdk' {");

  // KnownSecretKeys: union of all keys across all contexts
  const keySourceMap = buildKeySourceMap(contexts);
  lines.push('  interface KnownSecretKeys {');
  for (const [key, sources] of keySourceMap) {
    lines.push(`    /** From context: ${sources.join(', ')} */`);
    lines.push(`    ${formatProperty(key)}: string;`);
  }
  lines.push('  }');

  lines.push('');

  // ContextSecrets: each context with its specific secret keys as union type
  lines.push('  interface ContextSecrets {');
  for (const env of contexts) {
    if (env.keys.length === 0) {
      lines.push(`    ${formatProperty(env.name)}: never;`);
    } else {
      const keyUnion = env.keys.map((k) => `'${escapeQuotes(k)}'`).join(' | ');
      lines.push(`    ${formatProperty(env.name)}: ${keyUnion};`);
    }
  }
  lines.push('  }');

  lines.push('}');
  lines.push('');

  // A top-level export makes the generated .d.ts a TypeScript module, so the
  // `declare module '@kici-dev/sdk'` block above augments the SDK's interfaces
  // instead of being parsed as an ambient declaration that replaces (shadows)
  // the whole module.
  lines.push('export {};');
  lines.push('');

  return lines.join('\n');
}
