/**
 * Docker/Podman Compose service manager.
 *
 * Generates compose YAML files and manages service lifecycle via
 * `docker compose` or `podman compose` (auto-detected). Provides
 * a container-based service management backend that works on any
 * platform with Docker or Podman installed.
 */

import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { resolveImageRef } from './image-digests.js';
import type {
  ServiceManager,
  ServiceConfig,
  ServiceStatus,
  LogOptions,
  ServiceState,
  DiscoveredInstance,
  LaunchSpec,
} from './types.js';

/** Container runtime binary (`podman` or `docker`); compose form is `${runtime} compose`. */
type Runtime = 'podman' | 'docker';

/**
 * Detect which container runtime is available.
 * Tries podman compose first, then docker compose.
 *
 * Exported so the orchestrator installer can resolve the runtime once when
 * injecting the `KICI_DEPLOY_CONTAINER_RUNTIME` env var for a compose deploy.
 *
 * @throws When neither runtime is found.
 */
export function detectRuntime(): Runtime {
  try {
    execSync('podman compose version', { stdio: 'pipe' });
    return 'podman';
  } catch {
    // podman not available
  }

  try {
    execSync('docker compose version', { stdio: 'pipe' });
    return 'docker';
  } catch {
    // docker not available
  }

  throw new Error('No container runtime found. Install Docker or Podman with compose support.');
}

/**
 * Get the path to the compose file for a service.
 * Uses the directory of the env file (e.g., /etc/kici/) as the location.
 */
function getComposeFilePath(config: ServiceConfig): string {
  const dir = path.dirname(config.envFilePath);
  return path.join(dir, `${config.name}-compose.yaml`);
}

/**
 * Map compose container state strings to our ServiceState type.
 */
function mapContainerState(state: string): ServiceState {
  const lower = state.toLowerCase();
  if (lower === 'running') return 'running';
  if (lower === 'exited' || lower === 'stopped' || lower === 'dead') return 'stopped';
  if (lower === 'restarting' || lower === 'created') return 'stopped';
  return 'unknown';
}

/**
 * Map restart policy to compose restart mode.
 */
function getRestartMode(config: ServiceConfig): string {
  if (!config.restartPolicy.enabled) return 'no';
  return 'unless-stopped';
}

/**
 * Generate compose YAML content for a service.
 *
 * Uses a manual YAML builder to avoid adding a YAML library dependency.
 * The generated file includes the service definition with env_file,
 * restart policy, and volume mounts.
 *
 * The `image:` line is pinned by manifest-list digest via `resolveImageRef`
 * (`quay.io/kici-dev/<service-name>:<version>@sha256:<digest>`), falling back
 * to the mutable `:latest` tag only when no recorded digest ships with this
 * package. Source of truth for the publish targets:
 * packages/ci/src/publish-images.ts. See
 * .claude/rules/container-publish-registry.md — Quay is the sole registry for
 * public KiCI images we publish.
 */
function generateComposeYaml(config: ServiceConfig): string {
  const restartMode = getRestartMode(config);

  const lines = [
    '# Generated by KiCI service installer',
    `# Service: ${config.displayName}`,
    '',
    'services:',
    `  ${config.name}:`,
    `    image: ${resolveImageRef(config.name)}`,
    `    container_name: ${config.name}`,
    `    restart: ${restartMode}`,
    '    env_file:',
    `      - ${config.envFilePath}`,
    '    volumes:',
    `      - ${config.workingDirectory}:${config.workingDirectory}`,
    '    network_mode: host',
  ];

  if (config.component) {
    // Marker decoded by list() so podman/docker ps can classify the container's component.
    lines.push('    labels:');
    lines.push(`      dev.kici.component: ${config.component}`);
    // Deploy-folder marker so list() can recover the instanceDir straight from
    // the container labels, making the instance index a rebuildable cache.
    if (config.instanceDir) {
      lines.push(`      dev.kici.instance-dir: "${config.instanceDir}"`);
    }
  }

  return lines.join('\n') + '\n';
}

export class ComposeServiceManager implements ServiceManager {
  private runtime: Runtime | null = null;

  /** Get the runtime binary (`podman` or `docker`), detecting it if not already done. */
  private getRuntime(): Runtime {
    if (!this.runtime) {
      this.runtime = detectRuntime();
    }
    return this.runtime;
  }

  /** Run a compose command for the given service config. */
  private runCompose(config: ServiceConfig, args: string): void {
    const runtime = this.getRuntime();
    const composeFile = getComposeFilePath(config);
    execSync(`${runtime} compose -f "${composeFile}" ${args}`, { stdio: 'pipe' });
  }

  async install(config: ServiceConfig): Promise<void> {
    // Detect runtime first (will throw if neither available)
    this.getRuntime();

    // Ensure compose file directory exists
    const composeFile = getComposeFilePath(config);
    const dir = path.dirname(composeFile);
    fs.mkdirSync(dir, { recursive: true });

    // Generate and write compose file
    const yaml = generateComposeYaml(config);
    fs.writeFileSync(composeFile, yaml, 'utf-8');
  }

  async uninstall(config: ServiceConfig): Promise<void> {
    // Stop containers
    try {
      this.runCompose(config, 'down');
    } catch {
      // May already be down
    }

    // Remove compose file
    const composeFile = getComposeFilePath(config);
    if (fs.existsSync(composeFile)) {
      fs.unlinkSync(composeFile);
    }
  }

  async start(config: ServiceConfig): Promise<void> {
    this.runCompose(config, 'up -d');
  }

  async stop(config: ServiceConfig): Promise<void> {
    this.runCompose(config, 'down');
  }

  async restart(config: ServiceConfig): Promise<void> {
    this.runCompose(config, 'restart');
  }

  async status(config: ServiceConfig): Promise<ServiceStatus> {
    try {
      const runtime = this.getRuntime();
      const composeFile = getComposeFilePath(config);
      const output = execSync(`${runtime} compose -f "${composeFile}" ps --format json`, {
        stdio: 'pipe',
      }).toString();

      // Parse JSON output - can be a single object or array of objects
      const data = JSON.parse(output);
      const container = Array.isArray(data) ? data[0] : data;

      if (!container) {
        return { state: 'stopped' };
      }

      const state = mapContainerState(container.State || '');
      return { state };
    } catch {
      return { state: 'unknown' };
    }
  }

  async logs(config: ServiceConfig, options: LogOptions): Promise<void> {
    const args = ['logs'];

    if (options.follow) {
      args.push('--follow');
    }

    if (options.since) {
      args.push(`--since ${options.since}`);
    }

    args.push(config.name);

    try {
      this.runCompose(config, args.join(' '));
    } catch (err) {
      console.error(`Failed to read compose logs: ${err}`);
    }
  }

  async isInstalled(config: ServiceConfig): Promise<boolean> {
    const composeFile = getComposeFilePath(config);
    return fs.existsSync(composeFile);
  }

  async list(isUserLevel: boolean): Promise<DiscoveredInstance[]> {
    // Reuse the existing runtime detection from install/uninstall. A missing
    // runtime (or a probe that throws partway through) means "no KiCI
    // containers discoverable" — return [] cleanly so the caller can move on.
    let runtime: Runtime;
    try {
      runtime = this.getRuntime();
    } catch {
      return [];
    }

    let raw: string;
    try {
      raw = execSync(`${runtime} ps -a --filter label=dev.kici.component --format '{{json .}}'`, {
        encoding: 'utf-8',
      }).toString();
    } catch {
      return [];
    }

    const out: DiscoveredInstance[] = [];
    for (const line of raw.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      let row: unknown;
      try {
        row = JSON.parse(trimmed);
      } catch {
        continue;
      }
      if (!row || typeof row !== 'object') continue;
      const r = row as { Names?: unknown; Labels?: unknown };
      const labels = typeof r.Labels === 'string' ? r.Labels : '';
      const m = labels.match(/dev\.kici\.component=(orchestrator|agent)/);
      if (!m) continue;
      const name = typeof r.Names === 'string' ? r.Names : String(r.Names ?? '');
      if (!name) continue;
      const dirMatch = labels.match(/dev\.kici\.instance-dir=([^,]+)/);
      out.push({
        name,
        platform: 'compose',
        isUserLevel,
        component: m[1] as 'orchestrator' | 'agent',
        instanceDir: dirMatch?.[1],
      });
    }
    return out;
  }

  async readLaunchSpec(_config: ServiceConfig): Promise<LaunchSpec | null> {
    return null; // compose is image-tag pinned; npm-source upgrade not used here
  }
}
