import { describe, it, expect, vi, beforeEach } from 'vitest';
import { Hono } from 'hono';
import { createClusterNameRoutes } from './admin-cluster-name.js';
import { RbacEnforcer } from '../secrets/rbac.js';
import type { AccessLogRecord, AccessLogWriter } from '../audit/access-log.js';

vi.mock('../config/cluster-name.js', () => ({
  readClusterName: vi.fn(),
  setClusterName: vi.fn(),
}));

import { readClusterName, setClusterName } from '../config/cluster-name.js';

interface AccessLogStub {
  writer: Pick<AccessLogWriter, 'record'>;
  records: AccessLogRecord[];
}

function makeAccessLogStub(): AccessLogStub {
  const records: AccessLogRecord[] = [];
  return {
    writer: {
      record: async (entry: AccessLogRecord) => {
        records.push(entry);
      },
    },
    records,
  };
}

function buildTestApp(opts?: { accessLog?: Pick<AccessLogWriter, 'record'> }) {
  const inner = createClusterNameRoutes({
    db: {} as never,
    rbac: new RbacEnforcer(),
    accessLog: opts?.accessLog as AccessLogWriter | undefined,
  });
  const root = new Hono();
  root.use('*', async (c, next) => {
    c.set('role' as never, 'admin' as never);
    c.set('userId' as never, 'tester' as never);
    c.set('routingKey' as never, null as never);
    await next();
  });
  root.route('/', inner);
  return root;
}

describe('GET /cluster-name', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('returns clusterName with looksAutoGenerated=true for cluster-<6hex>', async () => {
    vi.mocked(readClusterName).mockResolvedValue('cluster-a3f9b1');
    const app = buildTestApp();
    const res = await app.request('/cluster-name', { method: 'GET' });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({
      clusterName: 'cluster-a3f9b1',
      looksAutoGenerated: true,
    });
  });

  it('returns clusterName with looksAutoGenerated=false for a renamed cluster', async () => {
    vi.mocked(readClusterName).mockResolvedValue('production-arm');
    const app = buildTestApp();
    const res = await app.request('/cluster-name', { method: 'GET' });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({
      clusterName: 'production-arm',
      looksAutoGenerated: false,
    });
  });

  it('returns 503 when cluster_name has not been resolved yet', async () => {
    vi.mocked(readClusterName).mockResolvedValue(null);
    const app = buildTestApp();
    const res = await app.request('/cluster-name', { method: 'GET' });
    expect(res.status).toBe(503);
  });
});

describe('PUT /cluster-name', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renames and records an access_log entry', async () => {
    vi.mocked(readClusterName).mockResolvedValue('cluster-a3f9b1');
    vi.mocked(setClusterName).mockResolvedValue('production');
    const accessLog = makeAccessLogStub();
    const app = buildTestApp({ accessLog: accessLog.writer });

    const res = await app.request('/cluster-name', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: 'production' }),
    });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({
      clusterName: 'production',
      prior: 'cluster-a3f9b1',
      reconnectRequired: true,
    });

    expect(setClusterName).toHaveBeenCalledOnce();
    expect(setClusterName).toHaveBeenCalledWith(expect.anything(), 'production');
    expect(accessLog.records).toHaveLength(1);
    expect(accessLog.records[0]).toMatchObject({
      orgId: null,
      action: 'cluster_name.update',
      target: { type: 'cluster_meta', id: 'cluster_name' },
      outcome: 'allowed',
      meta: { prior_value: 'cluster-a3f9b1', new_value: 'production' },
    });
  });

  it('does NOT record an access_log entry when the rename is a no-op', async () => {
    vi.mocked(readClusterName).mockResolvedValue('production');
    vi.mocked(setClusterName).mockResolvedValue('production');
    const accessLog = makeAccessLogStub();
    const app = buildTestApp({ accessLog: accessLog.writer });

    const res = await app.request('/cluster-name', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: 'production' }),
    });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({
      clusterName: 'production',
      prior: 'production',
      reconnectRequired: false,
    });
    expect(accessLog.records).toHaveLength(0);
  });

  it('rejects an invalid name with 400', async () => {
    const app = buildTestApp();
    const res = await app.request('/cluster-name', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: 'Bad_Name' }),
    });
    expect(res.status).toBe(400);
    expect(setClusterName).not.toHaveBeenCalled();
  });
});
