/**
 * Admin API routes for managing this orchestrator's cluster name
 * (`cluster_meta.cluster_name`).
 *
 * The cluster name is the human-friendly identifier that surfaces in
 * Platform's connection registry and in the dashboard's per-orch URL
 * segment (`/orgs/:cId/orchestrators/:clusterName/...`). Operators
 * read and rename it via `kici-admin cluster-name {get,set}`.
 *
 * Routes:
 *
 *   - `GET /api/v1/admin/cluster-name` →
 *     `{ clusterName: string, looksAutoGenerated: boolean }`
 *   - `PUT /api/v1/admin/cluster-name` → body `{ name: string }`,
 *     validates via the shared `clusterNameSchema` and persists.
 *     Returns `{ clusterName, prior }`. Renames are recorded in
 *     `access_log` so the audit trail captures who changed it and when.
 *
 * Mutation requires `secret.write` (same posture as the rest of
 * admin-org-settings). The orchestrator publishes the new name on the
 * next `source.register` — the route response includes a hint so the
 * CLI can tell the operator to reconnect to make Platform aware.
 */
import { Hono } from 'hono';
import type { Kysely } from 'kysely';
import { z } from 'zod';
import { createLogger, toErrorMessage } from '@kici-dev/shared';
import { CLUSTER_NAME_REGEX, clusterNameSchema } from '@kici-dev/engine/protocol/cluster-name';
import type { Database } from '../db/types.js';
import type { RbacEnforcer, Role } from '../secrets/rbac.js';
import { handleAdminError } from './admin-errors.js';
import { requireUnscopedToken } from '../secrets/routing-key-scope.js';
import { readClusterName, setClusterName } from '../config/cluster-name.js';
import type { AccessLogWriter } from '../audit/access-log.js';

const logger = createLogger({ prefix: 'admin-cluster-name' });

const AUTO_GENERATED_PATTERN = /^cluster-[0-9a-f]{6}$/;

interface ClusterNameRouteDeps {
  db: Kysely<Database>;
  rbac: RbacEnforcer;
  /**
   * Optional — when wired, each rename emits one `access_log` row
   * (`cluster_name.update`) with `orgId=null` carrying the prior + new
   * value in `meta`. Cluster-name is orch-scoped, not org-scoped, so
   * the row's `orgId` is null by design.
   */
  accessLog?: AccessLogWriter;
}

type AdminEnv = {
  Variables: {
    role: Role;
    userId: string;
    routingKey: string | null;
  };
};

const updateSchema = z.object({
  name: clusterNameSchema,
});

export function createClusterNameRoutes(deps: ClusterNameRouteDeps): Hono<AdminEnv> {
  const app = new Hono<AdminEnv>();

  app.get('/cluster-name', async (c) => {
    try {
      const denied = requireUnscopedToken(c);
      if (denied) return denied;
      deps.rbac.requirePermission(c.get('role'), 'secret.read');
      const current = await readClusterName(deps.db);
      if (current === null) {
        return c.json(
          {
            error: 'cluster_name not yet resolved. resolveAndPersistClusterName runs at orch boot.',
          },
          503,
        );
      }
      return c.json({
        clusterName: current,
        looksAutoGenerated: AUTO_GENERATED_PATTERN.test(current),
      });
    } catch (err) {
      logger.error('Failed to read cluster_name', { error: toErrorMessage(err) });
      return handleAdminError(c, err, logger);
    }
  });

  app.put('/cluster-name', async (c) => {
    try {
      const denied = requireUnscopedToken(c);
      if (denied) return denied;
      deps.rbac.requirePermission(c.get('role'), 'secret.write');
      const body = updateSchema.parse(await c.req.json());
      const prior = await readClusterName(deps.db);
      const updated = await setClusterName(deps.db, body.name);
      if (prior !== updated) {
        await deps.accessLog?.record({
          orgId: null,
          routingKey: null,
          actor: {
            type: 'service_account' as const,
            id: c.get('userId') as string,
          },
          action: 'cluster_name.update',
          target: { type: 'cluster_meta', id: 'cluster_name' },
          requestId: null,
          source: 'admin_http',
          outcome: 'allowed',
          meta: {
            prior_value: prior,
            new_value: updated,
          },
        });
        logger.info('Cluster name renamed', { prior, next: updated });
      }
      return c.json({
        clusterName: updated,
        prior,
        reconnectRequired: prior !== updated,
      });
    } catch (err) {
      logger.error('Failed to update cluster_name', { error: toErrorMessage(err) });
      return handleAdminError(c, err, logger);
    }
  });

  return app;
}

export { CLUSTER_NAME_REGEX };
