import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import os from 'node:os';
import fs from 'node:fs';
import { planePaths, planePorts } from './paths.js';

/**
 * Resolve a host address the plane's co-located bare-metal agent can reach for
 * cache-blob fetches. The orchestrator refuses to hand a scaler a loopback
 * storage URL (it assumes remote agents), so the plane advertises its first
 * non-internal IPv4 (still this machine — the agent is co-located). Falls back
 * to the hostname when no external interface is present.
 */
export function resolveAgentReachableHost(): string {
  for (const addrs of Object.values(os.networkInterfaces())) {
    for (const a of addrs ?? []) {
      if (a.family === 'IPv4' && !a.internal) return a.address;
    }
  }
  return os.hostname();
}

/**
 * Resolve the built `@kici-dev/orchestrator/standalone` entry the local plane
 * launches in independent (offline) mode.
 */
export function resolveStandaloneEntry(): string {
  const require = createRequire(import.meta.url);
  return require.resolve('@kici-dev/orchestrator/standalone');
}

/**
 * Resolve the built `@kici-dev/orchestrator/server` entry the local plane
 * launches in hybrid (Platform-attached) mode.
 */
export function resolveServerEntry(): string {
  const require = createRequire(import.meta.url);
  return require.resolve('@kici-dev/orchestrator/server');
}

/** Single `/ready` probe against the local orchestrator. */
export async function orchestratorReady(port: number): Promise<boolean> {
  try {
    const r = await fetch(`http://127.0.0.1:${port}/ready`);
    return r.status === 200;
  } catch {
    return false;
  }
}

/** Options threading the plane's admin token + bare-metal scaler into the boot. */
export interface SpawnOrchestratorOptions {
  /** Bootstrap admin token the CLI presents to the plane's admin API. */
  adminToken: string;
  /**
   * Local master secret key (64 hex chars). Enables the orchestrator's secrets
   * subsystem, which is what gates the admin API routes the CLI drives.
   */
  secretKey: string;
  /** Path to the bare-metal scaler YAML (KICI_SCALER_CONFIG_PATH). */
  scalerConfigFile: string;
  /**
   * Path to the dev-signed identity's EC P-256 private JWK (mode 0600), freshly
   * generated by the plane. Enables the orchestrator's local OIDC mint +
   * dev-signed provenance (issuer `kici-local`) in independent mode. Present in
   * the independent boot; omitted (with `attach`) in the hybrid boot, which
   * mints via the Platform relay instead.
   */
  devIdentityKeyFile?: string;
  /**
   * When present, boot the orchestrator in HYBRID mode attached to the Platform
   * relay instead of independent mode. OIDC + attestation then mint via the
   * Platform (the local dev signer is never consulted — the orchestrator's
   * `selectOidcMintRegistration` prefers the relay whenever a Platform
   * connection exists).
   */
  attach?: {
    /** Orchestrator KICI_PLATFORM_URL — a ws(s)://…/ws relay URL. */
    platformWsUrl: string;
    /** Org-scoped orchestrator key (kici_ok_…) presented on WS auth. */
    platformToken: string;
  };
}

/**
 * Spawn the orchestrator's standalone entry in independent mode against the
 * local Postgres, detached, with stdout/stderr redirected to the plane log.
 * Boots with a bootstrap admin token (so the CLI can drive the admin API) and a
 * bare-metal scaler (so a dispatched job auto-spawns an ephemeral agent). Waits
 * for `GET /ready` to report warm, then returns the child pid + port.
 */
export async function spawnOrchestrator(
  databaseUrl: string,
  opts: SpawnOrchestratorOptions,
): Promise<{ pid: number; port: number }> {
  const { orchestrator: port } = planePorts();
  const { logFile, root, cacheDir } = planePaths();
  fs.mkdirSync(root, { recursive: true });
  fs.mkdirSync(cacheDir, { recursive: true });
  const out = fs.openSync(logFile, 'a');
  // Strip every inherited KICI_* var: the plane fully specifies the
  // orchestrator's config below, and the orchestrator refuses to start on any
  // unknown KICI_* var (e.g. the plane's own KICI_LOCAL_* / KICI_CONFIG_DIR).
  const baseEnv: NodeJS.ProcessEnv = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (!key.startsWith('KICI_')) baseEnv[key] = value;
  }
  // Config common to both boots. The mode-specific keys (independent's
  // dev-signed identity vs hybrid's Platform relay) are layered on below.
  const commonEnv: NodeJS.ProcessEnv = {
    ...baseEnv,
    KICI_PORT: String(port),
    KICI_DATABASE_URL: databaseUrl,
    KICI_AGENT_AUTH: 'none',
    KICI_AUTO_MIGRATE: 'true',
    KICI_DATA_DIR: root,
    KICI_BOOTSTRAP_ADMIN_TOKEN: opts.adminToken,
    KICI_SECRET_KEY: opts.secretKey,
    KICI_SCALER_CONFIG_PATH: opts.scalerConfigFile,
    KICI_WEBHOOK_PUBLIC_URL: `http://127.0.0.1:${port}`,
    // Filesystem cache storage so ctx.cache save/restore works; the agent
    // fetches blobs from the plane's own /api/v1/cache/blob/ route.
    KICI_STORAGE_TYPE: 'filesystem',
    KICI_STORAGE_FS_PATH: cacheDir,
    KICI_STORAGE_FS_BASE_URL: `http://${resolveAgentReachableHost()}:${port}`,
  };

  let entry: string;
  let modeEnv: NodeJS.ProcessEnv;
  if (opts.attach) {
    // Hybrid: attach to the Platform relay. server.ts always builds the real
    // SecretResolver, and OIDC/attestation mint via the Platform relay (the
    // dev-signed identity envs are deliberately NOT set — the choke point
    // prefers the relay whenever a Platform connection exists).
    entry = resolveServerEntry();
    modeEnv = {
      KICI_MODE: 'hybrid',
      KICI_PLATFORM_URL: opts.attach.platformWsUrl,
      KICI_PLATFORM_TOKEN: opts.attach.platformToken,
    };
  } else {
    // Independent (offline): dispatch-time context-scoped secret resolution
    // (KICI_INDEPENDENT_SECRETS) plus the dev-signed identity (a local ES256
    // signer keyed to the freshly-generated keypair mints
    // `ctx.kici.oidc.token()` + `ctx.attestProvenance()` with issuer
    // `kici-local`, clearly non-prod). Only the local dev plane sets these.
    entry = resolveStandaloneEntry();
    modeEnv = {
      KICI_MODE: 'independent',
      KICI_INDEPENDENT_SECRETS: 'true',
      KICI_INDEPENDENT_IDENTITY: 'true',
      KICI_DEV_IDENTITY_KEY_FILE: opts.devIdentityKeyFile,
      KICI_PROVENANCE_ISSUER: 'kici-local',
    };
  }

  const child = spawn(process.execPath, [entry], {
    detached: true,
    stdio: ['ignore', out, out],
    env: { ...commonEnv, ...modeEnv },
  });
  child.unref();
  for (let i = 0; i < 120; i++) {
    if (await orchestratorReady(port)) return { pid: child.pid!, port };
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error('local orchestrator did not become ready');
}
