import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import { planePaths, planePorts } from './paths.js';
import { rotatePlaneLogIfOversized } from './plane-log.js';

/**
 * Resolve the built `@kici-dev/orchestrator/standalone` entry the local plane
 * launches in independent (offline) mode.
 */
export function resolveStandaloneEntry(): string {
  const require = createRequire(import.meta.url);
  return require.resolve('@kici-dev/orchestrator/standalone');
}

/**
 * Resolve the built `@kici-dev/orchestrator/server` entry the local plane
 * launches in hybrid (Platform-attached) mode.
 */
export function resolveServerEntry(): string {
  const require = createRequire(import.meta.url);
  return require.resolve('@kici-dev/orchestrator/server');
}

/**
 * Cap on one readiness probe. Generous enough for a server still warming up,
 * bounded so a socket that accepts and then goes silent cannot stall the poll
 * for the HTTP client's own multi-minute default — which would make
 * `awaitOrchestratorReady`'s attempt budget meaningless.
 */
const READY_PROBE_TIMEOUT_MS = 5_000;

/** Single `/ready` probe against the local orchestrator. */
export async function orchestratorReady(port: number): Promise<boolean> {
  try {
    const r = await fetch(`http://127.0.0.1:${port}/ready`, {
      signal: AbortSignal.timeout(READY_PROBE_TIMEOUT_MS),
    });
    return r.status === 200;
  } catch {
    return false;
  }
}

/** Options threading the plane's admin token + bare-metal scaler into the boot. */
export interface SpawnOrchestratorOptions {
  /** Bootstrap admin token the CLI presents to the plane's admin API. */
  adminToken: string;
  /**
   * Local master secret key (64 hex chars). Enables the orchestrator's secrets
   * subsystem, which is what gates the admin API routes the CLI drives.
   */
  secretKey: string;
  /** Path to the bare-metal scaler YAML (KICI_SCALER_CONFIG_PATH). */
  scalerConfigFile: string;
  /**
   * Path to the dev-signed identity's EC P-256 private JWK (mode 0600), freshly
   * generated by the plane. Enables the orchestrator's local OIDC mint +
   * dev-signed provenance (issuer `kici-local`) in independent mode. Present in
   * the independent boot; omitted (with `attach`) in the hybrid boot, which
   * mints via the Platform relay instead.
   */
  devIdentityKeyFile?: string;
  /**
   * When present, boot the orchestrator in HYBRID mode attached to the Platform
   * relay instead of independent mode. OIDC + attestation then mint via the
   * Platform (the local dev signer is never consulted — the orchestrator's
   * `selectOidcMintRegistration` prefers the relay whenever a Platform
   * connection exists).
   */
  attach?: {
    /** Orchestrator KICI_PLATFORM_URL — a ws(s)://…/ws relay URL. */
    platformWsUrl: string;
    /** Org-scoped orchestrator key (kici_ok_…) presented on WS auth. */
    platformToken: string;
  };
}

/**
 * Spawn the orchestrator entry against the local Postgres, detached, with
 * stdout/stderr redirected to the plane log, and return immediately. Boots with
 * a bootstrap admin token (so the CLI can drive the admin API) and a bare-metal
 * scaler (so a dispatched job auto-spawns an ephemeral agent).
 *
 * Returning before the process is ready is deliberate: it lets the caller record
 * the pid on disk BEFORE the readiness wait, so a wait that fails or a CLI that
 * dies mid-boot cannot leave a running orchestrator that nothing can identify.
 */
export function spawnOrchestratorProcess(
  databaseUrl: string,
  opts: SpawnOrchestratorOptions,
): { pid: number; port: number } {
  const { orchestrator: port } = planePorts();
  const { logFile, root, cacheDir } = planePaths();
  fs.mkdirSync(root, { recursive: true });
  fs.mkdirSync(cacheDir, { recursive: true });
  // Boot is the one moment nothing holds the log open, so it is where an
  // over-cap log can be rotated safely. The orchestrator that wrote it has
  // already been stopped by the caller's reclaim.
  rotatePlaneLogIfOversized(logFile);
  const out = fs.openSync(logFile, 'a');
  // Strip every inherited KICI_* var: the plane fully specifies the
  // orchestrator's config below, and the orchestrator refuses to start on any
  // unknown KICI_* var (e.g. the plane's own KICI_LOCAL_* / KICI_CONFIG_DIR).
  const baseEnv: NodeJS.ProcessEnv = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (!key.startsWith('KICI_')) baseEnv[key] = value;
  }
  // Config common to both boots. The mode-specific keys (independent's
  // dev-signed identity vs hybrid's Platform relay) are layered on below.
  const commonEnv: NodeJS.ProcessEnv = {
    ...baseEnv,
    KICI_PORT: String(port),
    KICI_DATABASE_URL: databaseUrl,
    KICI_AGENT_AUTH: 'none',
    // The plane is a single-machine affordance: everything it runs — the
    // orchestrator, its scalers, and the agents they spawn — lives on this
    // host. Binding loopback is what makes `KICI_AGENT_AUTH: 'none'` above safe
    // on a shared network, and `assertAgentAuthBindSafe` keeps it that way.
    KICI_HOST: '127.0.0.1',
    KICI_AUTO_MIGRATE: 'true',
    // The plane is exactly one orchestrator process, so Raft will never see a
    // coordinator peer. Declaring that up front sets the election grace period
    // to 0 (orchestrator-core: `config.cluster.singleNode ? 0 : …`), so the
    // node self-elects on its first election timer instead of deferring for the
    // 60s peer-discovery window. `/ready` answers 200 well before that window
    // closes — it reports the boot latch, not leadership — so a cold plane
    // otherwise looks up while a dispatch cannot land, and the CLI's own 60s
    // trigger budget expires first.
    KICI_CLUSTER_SINGLE_NODE: 'true',
    KICI_DATA_DIR: root,
    KICI_BOOTSTRAP_ADMIN_TOKEN: opts.adminToken,
    KICI_SECRET_KEY: opts.secretKey,
    KICI_SCALER_CONFIG_PATH: opts.scalerConfigFile,
    KICI_WEBHOOK_PUBLIC_URL: `http://127.0.0.1:${port}`,
    // Filesystem cache storage so ctx.cache save/restore works; the agent
    // fetches blobs from the plane's own /api/v1/cache/blob/ route.
    KICI_STORAGE_TYPE: 'filesystem',
    KICI_STORAGE_FS_PATH: cacheDir,
    KICI_STORAGE_FS_BASE_URL: `http://127.0.0.1:${port}`,
  };

  let entry: string;
  let modeEnv: NodeJS.ProcessEnv;
  if (opts.attach) {
    // Hybrid: attach to the Platform relay. server.ts always builds the real
    // SecretResolver, and OIDC/attestation mint via the Platform relay (the
    // dev-signed identity envs are deliberately NOT set — the choke point
    // prefers the relay whenever a Platform connection exists).
    entry = resolveServerEntry();
    modeEnv = {
      KICI_MODE: 'hybrid',
      KICI_PLATFORM_URL: opts.attach.platformWsUrl,
      KICI_PLATFORM_TOKEN: opts.attach.platformToken,
    };
  } else {
    // Independent (offline): dispatch-time context-scoped secret resolution
    // (KICI_INDEPENDENT_SECRETS) plus the dev-signed identity (a local ES256
    // signer keyed to the freshly-generated keypair mints
    // `ctx.kici.oidc.token()` + `ctx.attestProvenance()` with issuer
    // `kici-local`, clearly non-prod). Only the local dev plane sets these.
    entry = resolveStandaloneEntry();
    modeEnv = {
      KICI_MODE: 'independent',
      KICI_INDEPENDENT_SECRETS: 'true',
      KICI_INDEPENDENT_IDENTITY: 'true',
      KICI_DEV_IDENTITY_KEY_FILE: opts.devIdentityKeyFile,
      KICI_PROVENANCE_ISSUER: 'kici-local',
    };
  }

  const child = spawn(process.execPath, [entry], {
    detached: true,
    stdio: ['ignore', out, out],
    env: { ...commonEnv, ...modeEnv },
  });
  child.unref();
  return { pid: child.pid!, port };
}

/** Poll `/ready` until the orchestrator serves, or throw once the attempts run out. */
export async function awaitOrchestratorReady(
  port: number,
  attempts = 120,
  intervalMs = 500,
): Promise<void> {
  for (let i = 0; i < attempts; i++) {
    if (await orchestratorReady(port)) return;
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new Error('local orchestrator did not become ready');
}
