export * from '@kici-dev/core';
export * from './agent-platform.js';
export {
  encrypt,
  decrypt,
  deriveKey,
  generateMasterKey,
  type EncryptedValue,
} from './secret-crypto.js';
export { RingBuffer } from './ring-buffer.js';
export {
  CommandError,
  COMMAND_STDERR_TAIL_CHARS,
  stderrTail,
  toCommandError,
  type CommandContext,
  type CommandFailure,
} from './command-error.js';
// `redactConfig` / `scrubText` moved to @kici-dev/core (pure, CLI-reachable)
// and reach this barrel through the `export * from '@kici-dev/core'` above, so
// every existing `from '@kici-dev/shared'` import keeps resolving.
export { addLogsToArchive, MAX_LOG_BYTES } from './diagnostics/bundle-archive.js';
export {
  chunkBuffer,
  BundleChunkAssembler,
  ChunkRequestWaiter,
  FLEET_CHUNK_BYTES,
  type BundleChunkFrame,
} from './diagnostics/bundle-chunks.js';
export {
  createPool,
  createDb,
  closeDatabase,
  DEFAULT_DB_DRAIN_TIMEOUT_MS,
  isPoolAcquireTimeout,
  isBrokenConnectionError,
  retryOnBrokenConnection,
  type CloseDatabaseResult,
  type CreatePoolOptions,
  type PgPoolErrorSource,
  type PoolAcquireOutcome,
} from './db.js';
export { isPgUniqueViolation } from './pg-errors.js';
export {
  parseDatabaseUrl,
  maskDatabaseUrl,
  dropAndCreateDatabase,
  ensureDatabase,
  type EnsureDatabaseOpts,
  createDbRole,
  createReadOnlyDbUser,
  computeMigrationsHash,
  storeMigrationContentHash,
  readStoredMigrationContentHash,
  isSchemaCurrent,
  SchemaStatusKind,
  type SchemaStatus,
  clearDispatchQueueDirect,
  purgeStaleExecutionDirect,
  purgeStaleSourcesDirect,
  purgeScopedSecretsDirect,
  purgeContextsDirect,
  seedContextDirect,
  deleteContextDirect,
  seedContextBindingDirect,
  setContextPolicyDirect,
  listContextsDirect,
  showContextDirect,
  createContextTemplateDirect,
  setContextSecretDirect,
  listQueueDirect,
  showQueueEntryDirect,
  listExecutionRunsDirect,
  showExecutionRunDirect,
  listCheckRunTrackingDirect,
  listRegistrationsDirect,
  showRegistrationDirect,
  registerWorkflowManualDirect,
  resetRaftStateDirect,
  emitKiciEventDirect,
  purgeSecretBackendsDirect,
  prunePeerCredentialsDirect,
  type EventLogRow as PlatformEventLogRow,
  type OrgSettingsRepoPatternEntry,
  type EmitKiciEventOpts,
  REGISTERABLE_TRIGGER_TYPES,
  MIGRATION_HASH_TABLE,
  type PurgeStaleExecutionResult,
  type PurgeStaleSourcesResult,
  type SeedContextOpts,
  type SeedContextResult,
  type SeedContextBindingOpts,
  type SetContextPolicyOpts,
  type ContextRow,
  type ContextVariableRow,
  type ContextBindingRow,
  type ShowContextResult,
  type CreateContextTemplateOpts,
  type SetContextSecretOpts,
  type DispatchQueueRow,
  type ListQueueOpts,
  type ExecutionRunRow,
  type ExecutionJobRow,
  type ListExecutionRunsOpts,
  type CheckRunTrackingDirectRow,
  type ListCheckRunTrackingOpts,
  type WorkflowRegistrationRow,
  type ListRegistrationsOpts,
  type ListRegistrationsResult,
  type ShowRegistrationResult,
  type RegisterWorkflowManualOpts,
  type RegisterWorkflowManualResult,
} from './db-admin.js';
export {
  MIGRATION_TOOLING_TABLES,
  diffFingerprints,
  fingerprintSchema,
  formatDiffEntry,
  renderSnapshotModule,
  type ColumnFingerprint,
  type FingerprintDiffEntry,
  type SchemaFingerprint,
  type SqlQueryable,
} from './db-schema-fingerprint.js';
export { depCacheKeyOf, type DepCacheKey } from './dep-cache-key.js';
export { createMetricsRoutes, type MetricsRoutesDeps } from './routes/metrics.js';
export {
  createHealthRoutes,
  ReadinessStatus,
  type HealthRoutesDeps,
  type LivenessBase,
  type LivenessResponse,
  type ReadinessResponse,
  type BuildFingerprint,
  type AgentLivenessInfo,
} from './routes/health.js';
export { getReconnectDelay } from './reconnect-delay.js';
export {
  initTelemetry,
  getPrometheusExporter,
  collectRuntimeMetricNames,
  createMeter,
  type TelemetryConfig,
} from './telemetry/index.js';
export {
  setupGracefulShutdown,
  type ShutdownStep,
  type ShutdownLogger,
  type ShutdownHandle,
  type GracefulShutdownOptions,
} from './graceful-shutdown.js';
export { validateRequiredTools, type ToolRequirement } from './tool-check.js';
export {
  applyProxyKeepAliveTimeouts,
  PROXY_HEADERS_TIMEOUT_MS,
  PROXY_KEEP_ALIVE_TIMEOUT_MS,
  type KeepAliveTimeoutTarget,
} from './http-server-timeouts.js';
export {
  stopHttpServer,
  trackOpenSockets,
  DEFAULT_HTTP_STOP_GRACE_MS,
  type OpenSocketTracker,
  type StoppableServer,
} from './http-server-stop.js';
export { kiciTmpBase, kiciMkdtemp } from './tmp-dir.js';
export { createS3Client, type CreateS3ClientOptions, type SharedS3Config } from './s3-client.js';
export {
  assertColdStoreEnabled,
  BaseColdStore,
  ChunkLru,
  COLD_BUCKET_NAMES,
  DEFAULT_TABLE_CONFIG,
  chunkObjectKey,
  coldDaysToBucket,
  coldStoreArchiveBytesTotal,
  ColdStoreCycleResult,
  coldStoreArchiveCyclesTotal,
  coldStoreArchiveDurationSeconds,
  coldStoreArchiveRowsTotal,
  coldStorePurgeBytesTotal,
  coldStorePurgeChunksTotal,
  coldStorePurgeDurationSeconds,
  coldStoreRehydrateBytesTotal,
  coldStoreRehydrateDurationSeconds,
  coldStoreRehydrateRequestsTotal,
  coldStoreReplayDurationSeconds,
  coldStoreReplayRowsTotal,
  coldStoreVerifyFailuresTotal,
  computeChunkId,
  createColdStoreAdminOps,
  decodeChunk,
  encodeChunk,
  encodeKeySegment,
  isLongerColdRetention,
  parseManifest,
  PgTableAdapterBase,
  resolveTableConfig,
  serializeManifest,
  tablePrefix,
  tenantDayBucketPrefix,
  tenantDayPrefix,
  type ArchiveCycleSummary,
  type BaseColdStoreDeps,
  type BuiltColdStore,
  type ChunkCommitMetadata,
  type ChunkLruOptions,
  type ChunkManifest,
  type ColdBucketName,
  type ColdRetention,
  type ColdStore,
  type ColdStoreAdminChunkOpts,
  type ColdStoreAdminPurgeOpts,
  type ColdStoreAdminSide,
  type ColdStoreAdminStoreOpts,
  type ColdStoreConfig,
  type ColdStoreFetchRangeArgs,
  type ColdStoreReplayChunkArgs,
  type ColdStoreReplayResult,
  type ColdStoreReplayRowArgs,
  type ColdStoreTableConfig,
  type DbKind,
  type DecodeChunkArgs,
  type EligiblePartition,
  type EncodeChunkArgs,
  type EncodedChunk,
  type PurgeableChunk,
  type PurgeChunkResult,
  type PurgeExpiredChunksOpts,
  type PurgeExpiredChunksSummary,
  type TableAdapter,
} from './cold-store/index.js';
