export * from '@kici-dev/core';
export { RingBuffer } from './ring-buffer.js';
export { redactConfig, addLogsToArchive, MAX_LOG_BYTES } from './diagnostics/bundle-archive.js';
export {
  chunkBuffer,
  BundleChunkAssembler,
  ChunkRequestWaiter,
  FLEET_CHUNK_BYTES,
  type BundleChunkFrame,
} from './diagnostics/bundle-chunks.js';
export { createPool, createDb, type CreatePoolOptions, type PgPoolErrorSource } from './db.js';
export {
  parseDatabaseUrl,
  maskDatabaseUrl,
  dropAndCreateDatabase,
  dropDatabaseDirect,
  ensureDatabase,
  type EnsureDatabaseOpts,
  createDbRole,
  createReadOnlyDbUser,
  computeMigrationsHash,
  storeMigrationContentHash,
  readStoredMigrationContentHash,
  isSchemaCurrent,
  clearDispatchQueueDirect,
  purgeStaleExecutionDirect,
  purgeStaleSourcesDirect,
  purgeScopedSecretsDirect,
  seedEnvironmentDirect,
  deleteEnvironmentDirect,
  seedEnvironmentBindingDirect,
  setEnvironmentPolicyDirect,
  listEnvironmentsDirect,
  showEnvironmentDirect,
  createEnvironmentTemplateDirect,
  setEnvironmentSecretDirect,
  listQueueDirect,
  showQueueEntryDirect,
  listExecutionRunsDirect,
  showExecutionRunDirect,
  listExecutionJobsDirect,
  listRegistrationsDirect,
  showRegistrationDirect,
  registerWorkflowManualDirect,
  resetRaftStateDirect,
  emitKiciEventDirect,
  seedGenericWebhookSourceDirect,
  purgeSecretBackendsDirect,
  apiKeyExistsDirect,
  seedApiKeyInlineDirect,
  platformConnectionExistsDirect,
  countWebhookSourcesByConnectionIdDirect,
  getWebhookSourceByRoutingKeyDirect,
  findAnyUserApiKeyIdDirect,
  seedSyntheticGithubSourceDirect,
  seedWebhookSecretDirect,
  seedSourcePrivateKeyDirect,
  bumpRegistryVersionDirect,
  pollKiciEventsDirect,
  waitForPostgresDirect,
  waitForRunCompletionDirect,
  cleanupExecutionRowsDirect,
  isSchemaCurrentFromFilesDirect,
  storeMigrationContentHashInTableDirect,
  createJoinTokenDirect,
  updateSourceRoutingKeyDirect,
  prunePeerCredentialsDirect,
  waitForPlatformRegistrationsDirect,
  seedUniversalGitSourceDirect,
  seedCiSecurityFixturesDirect,
  // Stage 5c remainder helpers
  waitForExecutionRunStatusSinceDirect,
  latestExecutionRunByStatusDirect,
  waitForLatestExecutionJobStatusDirect,
  describeTableColumnsDirect,
  tableExistsDirect,
  insertKiciEventRawDirect,
  showKiciEventDirect,
  listKiciEventsDirect,
  deleteKiciEventsDirect,
  verifyKiciEventNotifyDirect,
  seedCrossRepoTrustDirect,
  listCrossRepoTrustBySourceRoutingKeyDirect,
  deleteCrossRepoTrustDirect,
  insertCrossRepoTrustStrictDirect,
  deleteWorkflowRegistrationsDirect,
  getWorkflowRegistrationByIdDirect,
  listRegistrationsByRoutingKeyDirect,
  waitForRegistrationsByRoutingKeyDirect,
  waitForRegistrationsUpdatedAtAdvanceDirect,
  updateWorkflowRegistrationCommitShaDirect,
  insertWorkflowRegistrationRawDirect,
  insertWorkflowRegistrationStrictDirect,
  getRegistryVersionDirect,
  bumpRegistryVersionSimpleDirect,
  upsertCronLastFiredDirect,
  countCronLastFiredDirect,
  insertCronLastFiredNowDirect,
  deleteCronLastFiredDirect,
  deleteExecutionRunsByWorkflowNameDirect,
  getGenericWebhookSourceByRoutingKeyDirect,
  listActiveGenericWebhookSourcesDirect,
  updateGenericWebhookVerificationConfigDirect,
  deleteGenericWebhookSourcesByNameDirect,
  restoreSoftDeletedGenericWebhookSourceDirect,
  upsertOrgSettingsGlobalWorkflowsDirect,
  updateOrgSettingsDeniedReposDirect,
  deleteOrgSettingsByCustomerIdDirect,
  getExecutionRunSecurityDirect,
  getHeldRunByIdDirect,
  listHeldRunApprovalsDirect,
  countHeldRunsByRunIdDirect,
  waitForPlatformExecutionRunStatusDirect,
  waitForPlatformEventLogDistinctRoutedDirect,
  waitForEventLogRowByDeliveryIdDirect,
  resolvePlatformWebhookSourceRoutingKeyDirect,
  ensureOrgOwnerMemberDirect,
  deletePeerCredentialsByInstanceIdLikeDirect,
  insertPeerCredentialExpiredDirect,
  getPeerCredentialRevokedAtDirect,
  listActivePeerCredentialsExcludingDirect,
  clearPeerCredentialsRevokedAtByIdsDirect,
  countActivePeerCredentialsByInstanceDirect,
  terminateIdleDbBackendsDirect,
  type ColumnInfo,
  type KiciEventRow,
  type CrossRepoTrustRow,
  type WorkflowRegistrationFullRow,
  type RegistrationsScopedResult,
  type LatestExecutionRunResult,
  type WaitForLatestJobResult,
  type ExecutionRunSecurityRow,
  type HeldRunSecurityRow,
  type EventLogRow as PlatformEventLogRow,
  type UpsertOrgSettingsOpts,
  type OrgSettingsRepoPatternEntry,
  type InsertKiciEventRawOpts,
  type EmitKiciEventOpts,
  type SeedGenericWebhookSourceOpts,
  REGISTERABLE_TRIGGER_TYPES,
  MIGRATION_HASH_TABLE,
  type PurgeStaleExecutionResult,
  type PurgeStaleSourcesResult,
  type SeedEnvironmentOpts,
  type SeedEnvironmentResult,
  type SeedEnvironmentBindingOpts,
  type SetEnvironmentPolicyOpts,
  type EnvironmentRow,
  type EnvironmentVariableRow,
  type EnvironmentBindingRow,
  type ShowEnvironmentResult,
  type CreateEnvironmentTemplateOpts,
  type SetEnvironmentSecretOpts,
  type DispatchQueueRow,
  type ListQueueOpts,
  type ExecutionRunRow,
  type ExecutionJobRow,
  type ListExecutionRunsOpts,
  type WorkflowRegistrationRow,
  type ListRegistrationsOpts,
  type ListRegistrationsResult,
  type ShowRegistrationResult,
  type RegisterWorkflowManualOpts,
  type RegisterWorkflowManualResult,
} from './db-admin.js';
export { createMetricsRoutes, type MetricsRoutesDeps } from './routes/metrics.js';
export { createHealthRoutes, type HealthRoutesDeps } from './routes/health.js';
export { getReconnectDelay } from './reconnect-delay.js';
export {
  initTelemetry,
  getPrometheusExporter,
  collectRuntimeMetricNames,
  createMeter,
  type TelemetryConfig,
} from './telemetry/index.js';
export {
  setupGracefulShutdown,
  type ShutdownStep,
  type ShutdownLogger,
  type ShutdownHandle,
  type GracefulShutdownOptions,
} from './graceful-shutdown.js';
export { validateRequiredTools, type ToolRequirement } from './tool-check.js';
export { createS3Client, type CreateS3ClientOptions, type SharedS3Config } from './s3-client.js';
export {
  BaseColdStore,
  ChunkLru,
  COLD_BUCKET_NAMES,
  DEFAULT_TABLE_CONFIG,
  chunkObjectKey,
  coldDaysToBucket,
  coldStoreArchiveBytesTotal,
  coldStoreArchiveCyclesTotal,
  coldStoreArchiveDurationSeconds,
  coldStoreArchiveRowsTotal,
  coldStorePurgeBytesTotal,
  coldStorePurgeChunksTotal,
  coldStorePurgeDurationSeconds,
  coldStoreRehydrateBytesTotal,
  coldStoreRehydrateDurationSeconds,
  coldStoreRehydrateRequestsTotal,
  coldStoreReplayDurationSeconds,
  coldStoreReplayRowsTotal,
  coldStoreVerifyFailuresTotal,
  computeChunkId,
  decodeChunk,
  encodeChunk,
  encodeKeySegment,
  isLongerColdRetention,
  parseManifest,
  resolveTableConfig,
  serializeManifest,
  tablePrefix,
  tenantDayBucketPrefix,
  tenantDayPrefix,
  type ArchiveCycleSummary,
  type BaseColdStoreDeps,
  type ChunkCommitMetadata,
  type ChunkLruOptions,
  type ChunkManifest,
  type ColdBucketName,
  type ColdRetention,
  type ColdStore,
  type ColdStoreConfig,
  type ColdStoreFetchRangeArgs,
  type ColdStoreReplayChunkArgs,
  type ColdStoreReplayResult,
  type ColdStoreReplayRowArgs,
  type ColdStoreTableConfig,
  type DbKind,
  type DecodeChunkArgs,
  type EligiblePartition,
  type EncodeChunkArgs,
  type EncodedChunk,
  type PurgeableChunk,
  type PurgeChunkResult,
  type PurgeExpiredChunksOpts,
  type PurgeExpiredChunksSummary,
  type TableAdapter,
} from './cold-store/index.js';
