import { describe, it, expect } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  existingTypesSource,
  hasLocalSecretFiles,
  mayReplace,
  sourceHeaderLabel,
} from './types-sources.js';

const header = (label: string) =>
  `// @generated by kici types -- DO NOT EDIT\n// Source: ${label}\n`;

describe('sourceHeaderLabel', () => {
  it('names each source', () => {
    expect(sourceHeaderLabel({ kind: 'orchestrator', url: 'http://h' })).toBe(
      'orchestrator http://h',
    );
    expect(sourceHeaderLabel({ kind: 'platform', orgId: 'o' })).toBe('Platform org o');
    expect(sourceHeaderLabel({ kind: 'local' })).toBe('local files');
  });
});

describe('existingTypesSource', () => {
  it('classifies each header', () => {
    expect(existingTypesSource(header('orchestrator http://h'))).toBe('remote');
    expect(existingTypesSource(header('Platform org o'))).toBe('remote');
    expect(existingTypesSource(header('local files'))).toBe('local');
    expect(existingTypesSource(header('offline stub -- no known secret keys'))).toBe('offline');
    expect(existingTypesSource(null)).toBe('none');
  });

  it('counts an older CLI header naming the Platform URL as remote', () => {
    // fails-when: a file written by an older CLI is treated as replaceable
    expect(existingTypesSource(header('https://api.kici.dev'))).toBe('remote');
  });

  it('counts a file with no header as remote', () => {
    expect(existingTypesSource("declare module '@kici-dev/sdk' {}\n")).toBe('remote');
  });
});

describe('mayReplace', () => {
  it('never lets local files replace a remote key set', () => {
    expect(mayReplace('remote', 'local')).toBe(false);
    expect(mayReplace('local', 'local')).toBe(true);
    expect(mayReplace('offline', 'local')).toBe(true);
    expect(mayReplace('none', 'local')).toBe(true);
  });

  it('lets the offline stub replace only a missing file or another stub', () => {
    expect(mayReplace('none', 'offline')).toBe(true);
    expect(mayReplace('offline', 'offline')).toBe(true);
    expect(mayReplace('local', 'offline')).toBe(false);
    expect(mayReplace('remote', 'offline')).toBe(false);
  });

  it('lets a remote key set replace anything', () => {
    // breaks-if-wrong: a fresh remote read must always refresh the file
    for (const existing of ['remote', 'local', 'offline', 'none'] as const) {
      expect(mayReplace(existing, 'remote')).toBe(true);
    }
  });
});

describe('hasLocalSecretFiles', () => {
  it('finds .secrets or secrets.yaml', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kici-tsrc-'));
    try {
      expect(await hasLocalSecretFiles(dir)).toBe(false);
      await fs.writeFile(path.join(dir, 'secrets.yaml'), 'production: {}\n');
      expect(await hasLocalSecretFiles(dir)).toBe(true);
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });
});
