/**
 * Cluster-name management commands for kici-admin.
 *
 * Subcommand namespace: `kici-admin cluster-name {get,set}`.
 *
 * The cluster name is the human-friendly identifier that surfaces on
 * Platform's connection registry and in the dashboard's per-orch URL
 * segment. Mutating it requires admin access (RBAC `secret.write`).
 *
 * Talks to the orchestrator admin API directly (not the Platform
 * dashboard proxy), so the CLI stays operable even when Platform is
 * unavailable. Backed by
 * `packages/orchestrator/src/routes/admin-cluster-name.ts`.
 */
import type { Command } from 'commander';
import type { AdminApiClient } from '../api-client.js';
import { toErrorMessage } from '@kici-dev/shared';
import { CLUSTER_NAME_FORMAT_MESSAGE } from '@kici-dev/engine/protocol/cluster-name';

interface ClusterNameResponse {
  clusterName: string;
  looksAutoGenerated: boolean;
}

interface UpdateResponse {
  clusterName: string;
  prior: string | null;
  reconnectRequired: boolean;
}

export function registerClusterNameCommands(
  program: Command,
  getClient: () => AdminApiClient,
): void {
  const cn = program
    .command('cluster-name')
    .description("Manage this orchestrator's cluster name (Platform-visible identifier)");

  cn.command('get')
    .description('Print the current cluster name.')
    .option('--format <format>', 'Output format: json|table', 'table')
    .action(async (opts: { format: string }) => {
      try {
        const response = await getClient().get<ClusterNameResponse>('/api/v1/admin/cluster-name');
        if (opts.format === 'json') {
          console.log(JSON.stringify(response, null, 2));
          return;
        }
        console.log(`Cluster name:        ${response.clusterName}`);
        console.log(`Looks auto-generated: ${response.looksAutoGenerated ? 'yes' : 'no'}`);
      } catch (err) {
        console.error(`Error: ${toErrorMessage(err)}`);
        process.exit(1);
      }
    });

  cn.command('set <name>')
    .description(`Rename the cluster. ${CLUSTER_NAME_FORMAT_MESSAGE}.`)
    .option('--format <format>', 'Output format: json|table', 'table')
    .action(async (name: string, opts: { format: string }) => {
      try {
        const response = await getClient().put<UpdateResponse>('/api/v1/admin/cluster-name', {
          name,
        });
        if (opts.format === 'json') {
          console.log(JSON.stringify(response, null, 2));
          return;
        }
        if (response.prior !== null && response.prior !== response.clusterName) {
          console.log(`Renamed: ${response.prior} -> ${response.clusterName}`);
        } else {
          console.log(`Cluster name is already ${response.clusterName} (no change).`);
        }
        if (response.reconnectRequired) {
          console.log(
            'Reconnect to Platform to publish the new name. Restart the orchestrator or run `kici-admin orchestrator-service restart`.',
          );
        }
      } catch (err) {
        console.error(`Error: ${toErrorMessage(err)}`);
        process.exit(1);
      }
    });
}
