/**
 * Render + install a git `post-receive` hook that triggers a KiCI run on every
 * push to a local filesystem (`file://`) source. The hook is a thin wrapper
 * around `kici-admin source trigger-local`; it carries no logic of its own.
 */
import { writeFileSync, chmodSync, existsSync } from 'node:fs';
import path from 'node:path';

/**
 * Render the post-receive hook script. For each pushed ref the hook calls
 * `kici-admin source trigger-local <id> --ref <ref> --sha <new> --base-url <url>`,
 * so a push to any branch dispatches a run for that ref.
 */
export function renderPostReceiveHook(opts: { sourceId: string; baseUrl: string }): string {
  return `#!/usr/bin/env bash
# KiCI local-source post-receive hook (generated by 'kici-admin source install-hook').
# Triggers a run for each pushed branch ref.
set -euo pipefail
while read -r _old _new ref; do
  kici-admin source trigger-local ${opts.sourceId} --ref "$ref" --sha "$_new" --base-url ${opts.baseUrl}
done
`;
}

/**
 * Write the rendered hook into the repo's `.git/hooks/post-receive` and make it
 * executable. Throws when the path is not a git repo (no `.git/hooks` dir).
 */
export function installPostReceiveHook(repoPath: string, script: string): string {
  const hooksDir = path.join(repoPath, '.git', 'hooks');
  if (!existsSync(hooksDir)) {
    throw new Error(`Not a git repo (no .git/hooks): ${repoPath}`);
  }
  const hookPath = path.join(hooksDir, 'post-receive');
  writeFileSync(hookPath, script, { mode: 0o755 });
  chmodSync(hookPath, 0o755);
  return hookPath;
}
